#!/bin/sh

#Author : Mouhamad KOREISSI
#Student at UCP

#This script does : 
#  - Create a github repository with a repository name as the current directory via the github API
#  - Add all the files of the directory to the repo
#  - Push it

usage() {
    echo "$0 [username] [private]"
    exit 2
}

#if [ $# -gt 2 ]; then
#    usage
#    exit 1
#fi

path=`pwd`
repo_name=`basename $path`
private=""
# u => username, p => private, P => Public
while getopts "u:s:" option; do
    case "${option}" in
        u) username=${OPTARG} ;;
        s) scope=${OPTARG} ;; 
        *) usage ;;
    esac
done
shift $((OPTIND-1))

#Choosing the scope of the repo (public or private)
if [ "$scope" == "private" ]; then
    private="true"
else
    if [ "$scope" == "public" ]; then
        private="false"
    fi
fi

#if a username is given the script will use it, otherwise will use the default user in the system
if [ ! -z "$username" -a "$username" != "" ]; then
    username=`git config github.user`
    if [ $username = "" ]; then
        usage
    fi
else
    usage
fi

echo "username : $username"
echo "scope : $scope"
echo "private : $private"
exit 0
#use a token if one is given, need the password otherwise
token=`git config github.token`
if [ $token = "" ]; then
    credentials="$username"    
else
    credentials="$username:$token"    
fi

echo "$path, $repo_name, $username, $credentials"

echo "Creating the repository $repo_name on Github..."
echo "Enter password : "
curl -u "$credentials" https://api.github.com/user/repos -d '{"name":"'$repo_name'", "private":'$private'}' > /dev/null 2>&1
git init
git add .
git commit -m "First commit"
echo "Pushing files to Github..."
git remote add origin https://www.github.com/$username/$repo_name
git remote -v
git push -u origin master

echo "Done."
