#!/bin/sh

#Author : Mouhamad KOREISSI
#Student at UCP

#This script does : 
#  - Create a github repository with a repository name as the current directory via the github API
#  - Add all the files of the directory to the repo
#  - Push it

usage() {
    echo "$0 -s scope [-u username]"
    exit 2
}

path=`pwd`
repo_name=`basename $path`

# u => username, p => private, P => Public
while getopts "u:s:" option; do
    case "${option}" in
        u) username=${OPTARG} ;;
        s) scope=${OPTARG} ;; 
        *) usage ;;
    esac
done
shift $((OPTIND-1))

#Choosing the scope of the repo (public or private)
if [ "$scope" == "private" ]; then
    private="true"
else
    if [ "$scope" == "public" ]; then
        private="false"
    fi
fi

#if a username is given the script will use it, otherwise will use the default git user in the system
if [ ! -z "$username" -a "$username" != "" ]; then
    username=`git config github.user`
    if [ $username = "" ]; then
        usage
    fi
else
    usage
fi

#use a token if one is available, need the password otherwise
token=`git config github.token`
[ -z $token ] && credentials="$username"
[ ! -z $token ] && credentials="$username:$token"

echo "Creating the repository $repo_name on Github..."

#Ask the password if token is not provided
[ -z $token ] && echo "Enter password : "

curl -u "$credentials" https://api.github.com/user/repos -d '{"name":"'$repo_name'", "private":'$private'}' > /dev/null 2>&1
#Exit if repo couldn't be created
[ $? -ne 0 ] && echo "Error : repo couldn't be created, check if internet connection available" && exit 3 

git init
git add .
git commit -m "First commit"
echo "Pushing files to Github..."
git remote add origin https://www.github.com/$username/$repo_name
git remote -v
git push -u origin master
[ $? -ne 0 ] && echo "Error : couldn't push, check if internet connection available" && exit 3 

echo "Repository $repo_name created."
